name: flutter_sakura_base
description: A Flutter project base by Sakura (https://github.com/sakura-sakai).

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For Architecture
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  state_notifier: ^0.7.2+1

  # For Navigation
  auto_route: ^3.2.4

  # For Networking
  dio: ^4.0.4
  connectivity_plus: ^2.2.1

  # For Auth
  ua_client_hints: ^1.1.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.13

  # For Model
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0

  # For env
  flutter_dotenv: ^5.0.2

  # For utils
  validators: ^3.0.0

  # For UIs
  cupertino_icons: ^1.0.2
  gap: ^2.0.0
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  video_player: ^2.2.19
  shimmer: ^2.0.0
  flutter_tts: ^3.3.3
  flutter_picker: ^2.0.3
  flutter_slidable: ^1.2.0
  percent_indicator: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7

  # For Analyzer
  flutter_lints: ^1.0.4

  # For Networking
  retrofit_generator: ^4.0.1

  # For Assets
  flutter_gen_runner: ^4.1.5

  # For Navigation
  auto_route_generator: ^3.2.3

  # For Model
  freezed: ^1.1.1

  # For Testing
  mocktail: any
  mocktail_image_network: any

flutter_gen:
  output: lib/ui/components/atom/assets_gen/
  integrations:
    flutter_svg: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
    - assets/videos/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
